/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#484555',
        primary: '#5b3cdd',
        'on-primary': '#ffffff',
        'primary-container': '#7459f7',
        'on-primary-container': '#fffbff',
        secondary: '#a7391e',
        'on-secondary': '#ffffff',
        'secondary-container': '#fd7958',
        'on-secondary-container': '#6e1500',
        tertiary: '#00647c',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#007f9c',
        'on-tertiary-container': '#fafdff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'franc-violet': '#7b61ff',
        'franc-green': '#27ae60',
        'franc-coral': '#ff7a59',
        'franc-pink': '#ff4e8e',
        'franc-blue': '#00d1ff',
        // Tonal "fixed" variants (Material3-style), matching the Stitch reference mockup
        // (mockups/landing.html) — used for light-tinted bento/hero surfaces.
        outline: '#797587',
        'outline-variant': '#c9c4d8',
        'surface-variant': '#e5e2e1',
        'primary-fixed': '#e5deff',
        'primary-fixed-dim': '#c9bfff',
        'on-primary-fixed': '#1a0063',
        'on-primary-fixed-variant': '#441cc8',
        'secondary-fixed': '#ffdad2',
        'secondary-fixed-dim': '#ffb4a2',
        'on-secondary-fixed': '#3c0700',
        'on-secondary-fixed-variant': '#862208',
        'tertiary-fixed': '#b7eaff',
        'tertiary-fixed-dim': '#4cd6ff',
        'on-tertiary-fixed': '#001f28',
        'on-tertiary-fixed-variant': '#004e60',
      },
      fontFamily: {
        'display-xl': ['Bricolage Grotesque', 'sans-serif'],
        'display-lg': ['Bricolage Grotesque', 'sans-serif'],
        'headline-lg': ['Bricolage Grotesque', 'sans-serif'],
        'headline-lg-mobile': ['Bricolage Grotesque', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'cta-pill': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'cta-pill': ['16px', { lineHeight: '1', fontWeight: '700' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
        bento: '2rem',
      },
      spacing: {
        base: '8px',
        'container-margin': '24px',
        'stack-gap': '16px',
        'section-padding': '40px',
        'grid-gutter': '20px',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
